### ISSUE TITLE
General remarks

### ISSUE THREAD

**Issue by loeiten** [yhoiseth/python-prediction-scorer#59]
Great work @yhoiseth, highly appreciated 👍 

Thought I could share my views on the project

- Although I share your view on the neatness of `Decimal` I see that it can be a hassle to type `Decimal` each time I want to add a prediction. For user-friendliness, have you considered allowing `float` together with `Decimal` in the type annotations?
- Can the `true_alternative_index` be defaulted to `1` for easier typing (as you see I have extremely lazy fingers 😄)?
- Could additional `actions` be used, for example:
    - ~~Some kind of coverage reporting~~ <- covered in #25 
    - [`bandit`](https://github.com/PyCQA/bandit) for security measures (for example is `assert` "unsafe") 
    - Other `PyQCA` linters like [`pylint`](https://github.com/PyCQA/pylint)
- Did you consider splitting the project to different files? My opinion is that this increases the readability (for example dedicating a file to the prediction-type classes)
- I got a bit confused about how the `ID` was used in the [Comparing scores over time](https://github.com/yhoiseth/python-prediction-scorer#comparing-scores-over-time). I understood it like "1 ID = 1 prediction", and that only the last prediction of that day is counted in the score over time
    - Would it make sense to make a database to aggregate the scores (it looks like everything is living in the memory of the runtime at the moment)
- Could more docstrings be used? I'm personally a sucker for (`numpydoc`)[https://numpydoc.readthedocs.io/en/latest/]
- Does it make sense to explicitly give the formula for the Brier score in the doc? I got quite confused of the concept in the start until I realized that this was nothing but the mean squared error
- I also see that you've used the issue tracker for transparency. Did you consider making a backlog in [projects](https://github.com/yhoiseth/python-prediction-scorer/projects)?

If you find any of these views reasonable, I'll gladly separate them to different issues 🙂

**Comment by yhoiseth** [comment]
> Great work @yhoiseth, highly appreciated 👍
> 
> Thought I could share my views on the project

Thanks, and thanks for taking the time to provide feedback!

>     * Although I share your view on the neatness of `Decimal` I see that it can be a hassle to type `Decimal` each time I want to add a prediction. For user-friendliness, have you considered allowing `float` together with `Decimal` in the type annotations?
> 
>     * Can the `true_alternative_index` be defaulted to `1` for easier typing (as you see I have extremely lazy fingers 😄)?

I‘m not sure if I understand the use case. I wouldn’t expect the library to be used much “raw,” but rather that one would, for example, write a script to score predictions from a spreadsheet. Then, you would do something like loop through the rows and score them. So you would only type the code once. But maybe I’m missing something?

>     * Could additional `actions` be used, for example:
>       
>       * ~Some kind of coverage reporting~ <- covered in #25
>       * [`bandit`](https://github.com/PyCQA/bandit) for security measures (for example is `assert` "unsafe")
>       * Other `PyQCA` linters like [`pylint`](https://github.com/PyCQA/pylint)

Yeah, definitely.

>     * Did you consider splitting the project to different files? My opinion is that this increases the readability (for example dedicating a file to the prediction-type classes)

Yeah, I agree. The architecture is far from ideal.

>     * I got a bit confused about how the `ID` was used in the [Comparing scores over time](https://github.com/yhoiseth/python-prediction-scorer#comparing-scores-over-time). I understood it like "1 ID = 1 prediction", and that only the last prediction of that day is counted in the score over time

I see. That should be more clear.

>       * Would it make sense to make a database to aggregate the scores (it looks like everything is living in the memory of the runtime at the moment)

Yeah, that could make sense. I’m hesitant to do it at the moment as it would make things more complicated, and it make more sense as a standalone project (that depends on this one).

>     * Could more docstrings be used? I'm personally a sucker for (`numpydoc`)[https://numpydoc.readthedocs.io/en/latest/]

Yeah, definitely. See #46.

>     * Does it make sense to explicitly give the formula for the Brier score in the doc? I got quite confused of the concept in the start until I realized that this was nothing but the mean squared error

Yeah, that’s a good point.

>     * I also see that you've used the issue tracker for transparency. Did you consider making a backlog in [projects](https://github.com/yhoiseth/python-prediction-scorer/projects)?

Yeah, that would probably be a good idea.

> If you find any of these views reasonable, I'll gladly separate them to different issues 🙂

That would be great 😄

**Comment by loeiten** [comment]
Sure, no problem :).
Closing this as the remarks has been moved to their own or related issues.
Just tell me if you'd like some help with some of the tasks.

**Comment by yhoiseth** [comment]
Thanks. I would love some help. But I have to warn you: I’m quite busy these days, so I can’t make any promises as to how quickly I will respond.
